version: '3'

services:
  mysql:
    container_name: app-mysql
    image: mysql
    ports:  
      - "3308:3306"
    networks:
      - my-network
    environment:
      - MYSQL_ROOT_PASSWORD=${VAL_MYSQL_ROOT_PWD}
      - MYSQL_USER=${VAL_MYSQL_USER}
      - MYSQL_PASSWORD=${VAL_MYSQL_PASSWORD}
      - MYSQL_DATABASE=${VAL_MYSQL_DATABASE}
  discovery: 
    container_name: app-disco
    image: localhost:5000/discoengine:${IMAGE_VARSION_DISCO_ENGINE}
    ports:  
      - "8010:8010"
    networks:
      - my-network
    volumes: 
      - ./config/discovery:/opt/config/
    depends_on: 
      - mysql
  gateway:
    container_name: app-gateway
    image: localhost:5000/gatewayengine:${IMAGE_VARSION_GATEWAY_ENGINE}
    ports:  
      - "8011:8011"
    networks:
      - my-network
    volumes: 
      - ./config/gatekeeper:/opt/config/
    depends_on: 
      - discovery 
      - mysql
    command: ["curl","-s","--fail","--show-error","http://app-disco:8010",">","/dev/null"]
    links:
      - "discovery"
  authengine:
    container_name: app-auth
    image: localhost:5000/authengine:${IMAGE_VARSION_AUTHENTICATION_ENGINE}
    networks:  
      - my-network
    volumes: 
      - ./config/authentication:/opt/config/
    depends_on: 
      - gateway
    command: ["curl","-s","--fail","--show-error","http://app-disco:8010",">","/dev/null"]

networks:
  my-network:
